[package]
name = "weeqwest"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
httparse = "1.0"
http = "0.1"
lazy_static = "1.0"

# TLS
rustls = {version = "0.14", default-features = false}
webpki = "0.18"
webpki-roots = "0.15"

# Client
mio = {version = "0.6", default-features = false, optional = true}
futures = {version = "0.1", optional = true}

[features]
default = ["client"]
client = ["mio", "futures"]
